### PR TITLE
Fixed reproducability issue with newer pytorch versions.

### PR DESCRIPTION
**Pull request by florianmai**
For Pytorch 1.0.0, you have to specify the aggregation of losses over the batch torch.nn.CrossEntropyLoss already when calling the constructor. Changing the attribute manually afterwards does not have an effect. This causes the reproducability issue in #96 , which my commit fixes.
It also fixes crashes that occur with PyTorch 1.0.0. due to improper access of scalar values.

### CODE REVIEW

**Comment by shawnkx** [comment]
@NadaOH how many epochs did you use to get that? Thanks!

**Comment by NadaOH** [comment]
@shawnkx  I used the same number of epochs, but I used the code from @florianmai  repository

**Comment by florianmai** [comment]
@NadaOH With more recent versions of PyTorch you will not get the exact same results as reported in the Infersent paper, which were produced with older versions of PyTorch. See here : https://pytorch.org/docs/stable/notes/randomness.html
I believe one major factor why it is not reproducible is that the order in which random numbers are generated changes. That's why with newer versions of PyTorch you do not get the same initialization of your weights as with previous versions.
The differences you observe (84.78 instead of 85 and 84.43 instead of 84.5) are very small and easily explainable by randomness in initialization.

**Comment by eedeleon** [comment]
What is the timeline on this PR being checked in ?

**Comment by aconneau** [comment]
Closing as train_nli.py was removed. Please refer to the [XLM repo](https://github.com/facebookresearch/XLM/blob/master/src/evaluation/glue.py#L117-L260) for training a model on NLI with much better performance.

**Pull request closed without merging**
